name: Linting, testing, building
on:
  push:
    branches: [ master ]

jobs:
  pipeline:
    strategy:
      matrix:
        os: [ macos-latest ]
        node: [ 18.14.x ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout master branch
        uses: actions/checkout@v3
      - name: Install packages
        run: npm ci
      - name: Production build
        run: npm run build:prod
      - name: Check by eslint
        run: npm run eslint
      - name: Check by style lint
        run: npm run lint:scss
      - name: Run unit tests
        run: npm run test:unit
      - name: Run storybook build
        run: npm run storybook:build
      - name: Run screenshot testing
        run: npm run test:ui:ci:macos
