name: Linting, testing, building
on:
  push:
    branches: [ master ]

jobs:
  pipeline:
    strategy:
      matrix:
        os: [ windows-latest ]
        node: [ 16.x ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout master branch
        uses: actions/checkout@v3
      - name: Install packages
        run: npm ci
      - name: Production build
        run: npm run build:prod
        if: always()
      - name: Check by eslint
        run: npm run eslint
        if: always()
      - name: Check by style lint
        run: npm run lint:scss
        if: always()
      - name: Run unit tests
        run: npm run test:unit
        if: always()
      - name: Run screenshot testing
        run: npm run test:ui:ci
        if: always()